# Generated by Django 4.2.7 on 2025-11-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_verificationtoken_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gemini_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
